-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users table
create table public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  role text default 'admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Workers table
create table public.workers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  age integer,
  gender text,
  aadhaar_number text unique,
  mobile_number text not null,
  address text,
  city text,
  state text,
  pincode text,
  district text,
  primary_skill text,
  experience integer,
  daily_wage numeric,
  availability text,
  additional_skills text,
  status text default 'pending',
  verified boolean default false,
  enrollment_date date default current_date,
  latitude numeric,
  longitude numeric,
  photo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Client Requests table
create table public.client_requests (
  id bigint generated by default as identity primary key,
  client_name text not null,
  client_phone text not null,
  client_email text,
  service_type text not null,
  location text not null,
  description text,
  budget numeric,
  urgency text default 'medium',
  status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Analytics table (simplified for Postgres, can be derived from workers usually but keeping for compatibility)
create table public.analytics (
  id bigint generated by default as identity primary key,
  date date not null,
  enrollments integer default 0,
  active_workers integer default 0,
  client_requests integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Worker Documents table
create table public.worker_documents (
  id bigint generated by default as identity primary key,
  worker_id bigint references public.workers(id) on delete cascade not null,
  document_type text not null,
  document_url text not null,
  verified boolean default false,
  uploaded_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS) - Optional but recommended
-- For now, we will enable it but allow all access since the backend handles auth
alter table public.users enable row level security;
alter table public.workers enable row level security;
alter table public.client_requests enable row level security;
alter table public.analytics enable row level security;
alter table public.worker_documents enable row level security;

create policy "Enable all access for authenticated users" on public.users for all using (true);
create policy "Enable all access for authenticated users" on public.workers for all using (true);
create policy "Enable all access for authenticated users" on public.client_requests for all using (true);
create policy "Enable all access for authenticated users" on public.analytics for all using (true);
create policy "Enable all access for authenticated users" on public.worker_documents for all using (true);
